import { useEffect, useState, type FormEvent } from "react";
import { api, json } from "../../lib/api";
import type { Message, Order } from "../../lib/types";
import { useAuth } from "../auth/AuthProvider";

const labels: Record<string, string> = { awaiting_payment: "Esperando pago", payment_submitted: "Pago enviado para revisión", awaiting_seller: "Esperando al vendedor", delivered: "Entrega marcada", completed: "Completado", disputed: "En disputa", awaiting_settlement: "Esperando conversión" };

export function OrdersPage() {
  const { account } = useAuth(); const [orders, setOrders] = useState<Order[]>([]); const [activeId, setActiveId] = useState<string>(); const [error, setError] = useState("");
  async function load() { try { const result = await api<Order[]>("/orders"); setOrders(result); setActiveId(current => current ?? result[0]?.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudieron cargar los pedidos."); } }
  useEffect(() => { void load(); }, []); const active = orders.find(order => order.id === activeId);
  return <section className="mx-auto max-w-7xl px-5 py-12"><p className="eyebrow">ÁREA PRIVADA</p><h1 className="mt-2 text-4xl font-bold">Mis pedidos</h1>{error && <p className="notice-error mt-4">{error}</p>}<div className="mt-8 grid gap-5 lg:grid-cols-[20rem_1fr]"> <aside className="card h-fit"><h2 className="font-semibold">Pedidos</h2><div className="mt-4 space-y-2">{orders.map(order => <button className={`order-row ${activeId === order.id ? "active" : ""}`} key={order.id} onClick={() => setActiveId(order.id)}><strong>{order.productTitle}</strong><span>{labels[order.status] ?? order.status}</span></button>)}{!orders.length && <p className="text-sm text-slate-400">Todavía no tienes pedidos.</p>}</div></aside><div className="card">{active ? <OrderDetail key={active.id} order={active} isSeller={active.sellerId === account?.id} onUpdated={updated => { setOrders(current => current.map(item => item.id === updated.id ? updated : item)); }} /> : <p className="page-state">Selecciona un pedido para ver los detalles y el chat.</p>}</div></div></section>;
}

function OrderDetail({ order, isSeller, onUpdated }: { order: Order; isSeller: boolean; onUpdated: (order: Order) => void }) {
  const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const [payment, setPayment] = useState(""); const [error, setError] = useState("");
  async function loadMessages() { try { setMessages(await api<Message[]>(`/orders/${order.id}/messages`)); } catch { /* Access is already verified by the order request. */ } }
  useEffect(() => { void loadMessages(); }, [order.id]);
  async function action(path: string, body?: unknown) { try { onUpdated(await api<Order>(path, { method: "POST", ...(body ? json(body) : {}) })); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible actualizar el pedido."); } }
  async function send(event: FormEvent) { event.preventDefault(); if (!text.trim()) return; try { await api(`/orders/${order.id}/messages`, { method: "POST", ...json({ text }) }); setText(""); await loadMessages(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo enviar el mensaje."); } }
  const amount = Number(order.paymentAmountUsdt ?? order.amount).toFixed(2);
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">PEDIDO</p><h2 className="mt-1 text-2xl font-bold">{order.productTitle}</h2><p className="mt-2 text-[#65717e]">{order.productGame} · {order.productType} · {order.productDelivery}</p></div><div className="text-right"><strong className="text-xl">{amount} USDT</strong><p className="mt-1 text-sm text-[#426d28]">{labels[order.status] ?? order.status}</p></div></div>{error && <p className="notice-error mt-5">{error}</p>}{!isSeller && order.status === "awaiting_payment" && <div className="mt-6 rounded-[8px] border border-[#dce1dc] bg-[#f7f8f6] p-4"><p className="font-semibold">Pago USDT TRC20</p><p className="mt-2 break-all text-sm text-[#65717e]">{order.depositAddress}</p><div className="mt-3 flex gap-2"><input className="field" value={payment} onChange={event => setPayment(event.target.value)} placeholder="Hash TRC20 o referencia Binance" /><button className="button-primary" onClick={() => void action(`/orders/${order.id}/payment`, { transactionId: payment })}>Enviar</button></div></div>}{isSeller && order.status === "awaiting_seller" && <button className="button-primary mt-6" onClick={() => void action(`/orders/${order.id}/deliver`)}>Marcar entrega realizada</button>}{!isSeller && order.status === "delivered" && <button className="button-primary mt-6" onClick={() => void action(`/orders/${order.id}/confirm`)}>Confirmar recepción</button>}<section className="mt-8 border-t border-[#dce1dc] pt-6"><h3 className="font-semibold">Chat del pedido</h3><div className="mt-4 max-h-72 space-y-3 overflow-auto">{messages.map(message => <article className={message.senderId === (isSeller ? order.sellerId : order.buyerId) ? "message mine" : "message"} key={message.id}><strong>{message.sender}</strong><p>{message.text}</p></article>)}</div><form className="mt-4 flex gap-2" onSubmit={send}><input className="field" value={text} onChange={event => setText(event.target.value)} maxLength={1000} placeholder="Escribe un mensaje" /><button className="button-primary">Enviar</button></form></section></div>;
}
