import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { api, json } from "../../lib/api";
import type { Account } from "../../lib/types";
import { useAuth } from "../auth/AuthProvider";

export function AccountPage({ reset = false }: { reset?: boolean }) {
  const [params] = useSearchParams(); const [mode, setMode] = useState(reset ? "reset" : params.get("mode") === "register" ? "register" : "login"); const [status, setStatus] = useState(""); const [resetRequested, setResetRequested] = useState(false); const navigate = useNavigate(); const { refresh } = useAuth();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { if (mode === "reset") { await api(resetRequested ? "/auth/reset-password" : "/auth/request-password-reset", { method: "POST", ...json(data) }); if (resetRequested) { setStatus("Contraseña actualizada. Ya puedes iniciar sesión."); setMode("login"); } else { setResetRequested(true); setStatus("Código enviado. Escribe el código y tu nueva contraseña."); } return; } const account = await api<Account>(`/auth/${mode === "login" ? "login" : "register"}`, { method: "POST", ...json(data) }); await refresh(); navigate(account.emailVerified ? (account.role === "seller" ? "/seller/offers" : "/marketplace") : "/verify-email"); } catch (error) { setStatus(error instanceof Error ? error.message : "No fue posible completar la solicitud."); } }
  return <section className="grid min-h-[calc(100vh-141px)] md:grid-cols-[.85fr_1.15fr]"><div className="bg-[#dfe9e2] px-[9vw] py-20 md:py-40"><p className="eyebrow">ACCESO SEGURO</p><h1 className="mt-4 text-5xl font-bold leading-[.96] tracking-[-3px] md:text-6xl">Tu cuenta,<br /><span className="font-normal text-[#647c92]">tus ofertas.</span></h1><p className="mt-5 max-w-[290px] text-sm leading-relaxed text-[#52616e]">Gestiona compras, ventas y conversaciones desde un mismo lugar.</p></div><div className="flex items-center px-[8vw] py-16"><form className="card w-full space-y-4" onSubmit={submit}><h2 className="text-2xl font-bold">{mode === "login" ? "Iniciar sesión" : mode === "register" ? "Crear cuenta" : "Recuperar contraseña"}</h2>{mode === "register" && <input className="field" name="name" required maxLength={30} placeholder="Nombre público" />}<input className="field" name="email" type="email" required placeholder="Correo electrónico" autoComplete="email" />{mode !== "reset" && <input className="field" name="password" type="password" required minLength={8} placeholder="Contraseña" autoComplete={mode === "login" ? "current-password" : "new-password"} />}{mode === "reset" && resetRequested && <><input className="field" name="code" required inputMode="numeric" maxLength={6} placeholder="Código de 6 dígitos" /><input className="field" name="password" type="password" required minLength={8} placeholder="Nueva contraseña" autoComplete="new-password" /></>}{mode === "register" && <><select className="field" name="role" defaultValue={params.get("role") ?? "buyer"}><option value="buyer">Comprador</option><option value="seller">Vendedor</option></select><label className="flex gap-2 text-sm text-[#52616e]"><input name="acceptTerms" required type="checkbox" />Acepto las reglas del mercado.</label></>}<button className="button-primary w-full">{mode === "login" ? "Entrar" : mode === "register" ? "Crear cuenta" : resetRequested ? "Cambiar contraseña" : "Enviar código"}</button>{status && <p className="text-sm text-[#a23e2c]">{status}</p>}<div className="flex justify-between text-sm text-[#65717e]">{mode !== "login" && <button type="button" onClick={() => setMode("login")}>Ya tengo cuenta</button>}{mode !== "register" && !reset && <button type="button" onClick={() => setMode("register")}>Crear cuenta</button>}{mode === "login" && <Link to="/forgot-password">Olvidé mi contraseña</Link>}</div></form></div></section>;
}

export function VerifyEmailPage() { const [code, setCode] = useState(""); const [status, setStatus] = useState(""); const navigate = useNavigate(); const { refresh } = useAuth(); async function verify(event: FormEvent) { event.preventDefault(); try { await api("/auth/verify-email", { method: "POST", ...json({ code }) }); await refresh(); navigate("/"); } catch (error) { setStatus(error instanceof Error ? error.message : "Código inválido."); } } return <section className="narrow-page"><form className="card space-y-4" onSubmit={verify}><p className="eyebrow">VERIFICACIÓN DE CORREO</p><h1 className="text-3xl font-bold">Confirma tu cuenta</h1><input className="field" value={code} onChange={event => setCode(event.target.value)} required inputMode="numeric" maxLength={6} placeholder="Código de 6 dígitos" /><button className="button-primary w-full">Verificar correo</button>{status && <p className="text-sm text-amber-200">{status}</p>}</form></section>; }

export function ProfilePage() { const { account, refresh, signOut } = useAuth(); const [name, setName] = useState(account?.name ?? ""); const [status, setStatus] = useState(""); async function save(event: FormEvent) { event.preventDefault(); try { await api("/profile", { method: "PATCH", ...json({ name }) }); await refresh(); setStatus("Perfil actualizado."); } catch (error) { setStatus(error instanceof Error ? error.message : "No fue posible actualizar el perfil."); } } return <section className="narrow-page"><form className="card space-y-4" onSubmit={save}><p className="eyebrow">CUENTA PERSONAL</p><h1 className="text-3xl font-bold">Mi perfil</h1><label className="label">Nombre público<input className="field" value={name} onChange={event => setName(event.target.value)} required minLength={3} maxLength={30} /></label><label className="label">Correo<input className="field opacity-60" value={account?.email ?? ""} disabled /></label><p className="text-sm text-slate-400">Cuenta de {account?.role === "seller" ? "vendedor" : "comprador"} · {account?.emailVerified ? "correo verificado" : "correo pendiente"}</p><button className="button-primary w-full">Guardar cambios</button><button className="button-secondary w-full" type="button" onClick={() => void signOut()}>Cerrar sesión</button>{status && <p className="text-sm text-slate-300">{status}</p>}</form></section>; }

interface SellerProfile { name: string; verified: boolean; completedTrades: number; averageRating: number | null; reviewCount: number; activeOffers: Array<{ id: string; title: string; game: string; type: string; price: number; delivery: string }>; reviews: Array<{ id: string; buyer: string; rating: number; comment: string }>; }
export function SellerProfilePage() { const { sellerId = "" } = useParams(); const [seller, setSeller] = useState<SellerProfile | null>(null); const [error, setError] = useState(""); useEffect(() => { api<SellerProfile>(`/sellers/${sellerId}`).then(setSeller).catch(reason => setError(reason instanceof Error ? reason.message : "No se pudo cargar el perfil.")); }, [sellerId]); if (error) return <section className="narrow-page"><p className="notice-error">{error}</p></section>; return <section className="mx-auto max-w-5xl px-5 py-12">{seller ? <><p className="eyebrow">PERFIL DE VENDEDOR</p><h1 className="mt-2 text-4xl font-bold">{seller.name} {seller.verified && <span className="text-lime-300">Verificado</span>}</h1><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Trades completados" value={seller.completedTrades} /><Metric label="Calificación" value={seller.averageRating ?? "Sin reseñas"} /><Metric label="Reseñas" value={seller.reviewCount} /></div><section className="mt-8"><h2 className="text-2xl font-semibold">Ofertas activas</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{seller.activeOffers.map(offer => <article className="card" key={offer.id}><p className="text-sm text-lime-300">{offer.game} · {offer.type}</p><h3 className="mt-1 font-semibold">{offer.title}</h3><p className="mt-2 text-slate-400">${Number(offer.price).toFixed(2)} · {offer.delivery}</p></article>)}</div></section><section className="mt-8"><h2 className="text-2xl font-semibold">Reseñas verificadas</h2><div className="mt-4 space-y-3">{seller.reviews.map(review => <article className="card" key={review.id}><strong>{"★".repeat(review.rating)} <span className="text-slate-300">{review.buyer}</span></strong><p className="mt-2 text-slate-400">{review.comment}</p></article>)}{!seller.reviews.length && <p className="text-slate-400">Este vendedor todavía no tiene reseñas.</p>}</div></section></> : <p className="page-state">Cargando perfil...</p>}</section>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="card"><strong className="text-3xl">{value}</strong><p className="mt-1 text-sm text-slate-400">{label}</p></article>; }

const legal: Record<string, string> = { "Reglas del mercado": "GameTrade conecta compradores y vendedores. Revisa toda oferta antes de solicitarla, conserva evidencia en el chat y no compartas credenciales de juegos.", Privacidad: "Guardamos datos necesarios para operar el mercado: perfil, ofertas, pedidos, mensajes y registros de pago. Nunca compartas contraseñas ni códigos de verificación.", "Compras y reembolsos": "Confirma la recepción solo después de recibir exactamente lo acordado. Si existe un problema, conserva evidencia y abre una disputa antes de confirmar.", "Ayuda y soporte": "Para asistencia sobre tu cuenta, pedidos o disputas escribe a gametradegg8@gmail.com." };
export function LegalPage({ title }: { title: string }) { return <section className="narrow-page"><article className="card"><p className="eyebrow">INFORMACIÓN</p><h1 className="mt-2 text-4xl font-bold">{title}</h1><p className="mt-6 text-lg leading-8 text-slate-300">{legal[title]}</p></article></section>; }
export function NotFoundPage() { return <section className="narrow-page"><div className="card"><h1 className="text-3xl font-bold">Página no encontrada</h1><Link className="button-primary mt-6 inline-block" to="/">Volver al inicio</Link></div></section>; }
